config/routes.rb
Monitor1c::Application.routes.draw do

  resources :stock_tests do
    resources :stock_differences

  end

  resources :nullarticles_tests

  resources :all_tests

  resources :lots_tests
  resources :articles_tests
  resources :sfptu_tests
  resources :rcvbls_tests

  resources :abstract_documents
  resources :stocks
  resources :organizations

  resources :tests_dashboard

  root to: 'tests_dashboard#index'

end

app/models/abstract_test.rb
class AbstractTest < ActiveRecord::Base
  # attr_accessible :title, :body
  self.table_name = 'docTests'

  belongs_to :stock

  def ok?
  	differences.count == 0
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  # attr_accessible :title, :body
  self.table_name = 'vwArticles'
  self.primary_key = 'id'

  def rref_bin()
  	"0x#{id.unpack('H*').join}"
  end
end

app/models/articles_test.rb
class ArticlesTest < AbstractTest
  # attr_accessible :title, :body
  has_many :differences, class_name: 'ArticlesDifference', foreign_key: 'test_id'
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  self.table_name = 'vwContracts'
  self.primary_key = '_IDRRef'

  belongs_to :contractor

  def code()
  	_Code
  end

  def title()
  	_Description
  end
end

app/models/contractor.rb
class Contractor < ActiveRecord::Base
  self.table_name = 'vwContractors'
  self.primary_key = '_IDRRef'

  has_many :contracts

  def code()
  	_Code
  end

  def title()
  	_Description
  end
end

app/models/lot_document.rb
class LotDocument < AbstractDocument
  # attr_accessible :title, :body
  self.inheritance_column = :_type_disabled

  has_many :movements, class_name: 'LotMovement', foreign_key: 'acceptDocId', primary_key: 'rref'
end

app/models/lot_movement.rb
class LotMovement < ActiveRecord::Base
  # attr_accessible :title, :body
  self.table_name = 'regLotMovements'

  belongs_to :test
  belongs_to :lot, class_name: 'LotDocument', foreign_key: 'acceptDocId', primary_key: 'rref'
  belongs_to :movementDoc, class_name: 'AbstractDocument', foreign_key: '_RecorderRRef', primary_key: 'rref'
  belongs_to :article, foreign_key: 'articleId'
end

app/models/lots_difference.rb
class LotsDifference < ActiveRecord::Base
  # attr_accessible :title, :body
  self.table_name = 'regLots'

  belongs_to :test, class_name: 'LotsTest'
  belongs_to :lot, class_name: 'AbstractDocument', primary_key: 'rref'
  belongs_to :article
end

app/models/lots_test.rb
class LotsTest < AbstractTest
  # attr_accessible :title, :body
  has_many :differences, class_name: 'LotsDifference', foreign_key: 'test_id'
  has_many :movements, class_name: 'LotMovement', foreign_key: 'test_id', order: '_RecorderRRef'
  has_many :lots, class_name: 'LotDocument', through: :movements, uniq: true

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  self.table_name = 'metaOrganizations'

  has_many :tests, class_name: 'AbstractTest', foreign_key: 'organization_id'
  has_many :rcvbls_tests
  has_many :differences, through: :rcvbls_tests

  def title
  	orgTitle
  end
end

app/models/rcvbls_test.rb
class RcvblsTest < AbstractTest
  has_many :differences, class_name: 'RcvblsDifference', foreign_key: 'test_id'
end

app/models/sfptu_difference.rb
class SfptuDifference < ActiveRecord::Base
  self.table_name = 'regPtuSfDifferences'

  belongs_to :test, class_name: 'SfptuTest', foreign_key: 'test_id'
  belongs_to :sfDoc, class_name: 'AbstractDocument', foreign_key: 'sfRRef', primary_key: 'rref'
  belongs_to :ptuDoc, class_name: 'AbstractDocument', foreign_key: 'ptuRRef', primary_key: 'rref'

end

app/models/sfptu_test.rb
class SfptuTest < AbstractTest
  has_many :differences, class_name: 'SfptuDifference', foreign_key: 'test_id', order: 'sfRRef'
end

app/models/stock.rb
# encoding: utf-8
class Stock < ActiveRecord::Base
  # attr_accessible :title, :body
  self.table_name = 'metaStocks'
  # self.primary_key = 'stockId'

  has_many :differences, foreign_key: 'stock_id', class_name: 'StockDifference', primary_key: 'stockId'
  has_many :documents, through: :differences, uniq: true

  has_many :tests, class_name: 'AbstractTest', primary_key: 'stockId', conditions: 'is_current=1'

  def title
  	cmpTitle
  end

  def tests_ok?
  	ok = true
  	tests.each do |t|
  		ok = false if !t.ok?
  	end

  	ok
  end

end

app/models/stock_difference.rb
# encoding: utf-8
class StockDifference < ActiveRecord::Base
  # attr_accessible :title, :body
  self.table_name = 'regStock'
  self.primary_key = 'id'

  belongs_to :stock, primary_key: 'stockId'
  belongs_to :article
  belongs_to :test, class_name: 'StockTest'
  has_many :movements, class_name: 'StockMovement', primary_key: [:stock_id, :article_id], foreign_key: [:stock_id, :article_id]
  has_many :documents, through: :movements, uniq: true
end

app/models/stock_movement.rb
class StockMovement < ActiveRecord::Base
  # attr_accessible :title, :body
  self.table_name = 'regStockMovements'
  
  belongs_to :difference, class_name: 'StockDifference', foreign_key: [:stock_id, :article_id], primary_key: [:stock_id, :article_id]
  belongs_to :stock
  belongs_to :article
  belongs_to :test, class_name: 'StockTest'
  belongs_to :document, class_name: 'AbstractDocument', foreign_key: '_RecorderRRef', primary_key: 'rref'

  def render_article
  	if !article.nil? 
  		"#{article.code} #{article.title}"
  	else
  		"[#{article_id}]"
  	end
  end

end

app/models/stock_test.rb
class StockTest < AbstractTest
  # attr_accessible :title, :body
  
  has_many :differences, class_name: 'StockDifference', foreign_key: 'test_id'
  has_many :movements, class_name: 'StockMovement', foreign_key: 'test_id'
  has_many :stocks, through: :differences, uniq: true
  has_many :documents, through: :movements, conditions: 'fixed=0', uniq: true
end

app/controllers/tests_dashboard_controller.rb
# encoding: utf-8
class TestsDashboardController < ApplicationController
	def index
		@articles_tests = ArticlesTest.where('tested=1').order('id')
		@stock_tests = StockTest.where('tested=1').order('id')
		@lots_tests = LotsTest.where('tested=1').order('id')
		@sfptu_tests = SfptuTest.where('tested=1 AND is_current=1').order('id')
		@rcvbls_tests = RcvblsTest.where('is_current=1').order('id')
		@all_tests = AbstractTest.where('tested=1').order('id')

		@stocks = Stock.all
		@organizations = Organization.where('orgAbbr IS NOT NULL').order('orgTitle')
	end
end

app/helpers/all_tests_helper.rb
module AllTestsHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/tests_dashboard_helper.rb
module TestsDashboardHelper
end

app/views/tests_dashboard/index.html.erb
<h1>Центральная панель тестирования</h1>
<h2>Тесты по типу метаданных</h2>
<table class="table table-condensed">
	<thead>
		<th>Тип теста</th>
		<th>Статус</th>
		<th>Расхождения</th>
	</thead>
	<tbody>
		<%
			differences = 0
			@articles_tests.each do |t|
				differences += t.differences.count
			end
		 %>
		 <tr class="<%= (differences > 0 ? 'error' : 'success') %>">
		 	<td>Номенклатурный справочник</td>
		 	<td><i class="<%= (differences > 0 ? 'icon-remove' : 'icon-ok') %>"></i></td>
		 	<td><%= differences %></td>
		 </tr>
		 <%
		 	differences = 0
		 	documents = 0
		 	@stock_tests.each do |t|
		 		differences += t.differences.count
		 		documents += t.documents.count
		 	end
		 %>
		 <tr class="<%= (differences > 0 ? 'error' : 'success') %>">
		 	<td><%= link_to 'Регистр товаров на складах', stock_tests_path %></td>
		 	<td><i class="<%= (differences > 0 ? 'icon-remove' : 'icon-ok') %>"></i></td>
		 	<td><%= "#{differences} (#{documents} документов)" %></td>
		 </tr>
		 <%
		 	differences = 0
		 	@lots_tests.each do |t|
		 		differences += t.differences.count
		 	end
		 %>
		 <tr class="<%= (differences > 0 ? 'error' : 'success') %>">
		 	<td><%= link_to 'Регистр партий товаров на складах', lots_tests_path %></td>
		 	<td><i class="<%= (differences > 0 ? 'icon-remove' : 'icon-ok') %>"></i></td>
		 	<td><%= "#{differences}" %></td>
		 </tr>
		 <%
		 	differences = 0
		 	@sfptu_tests.each do |t|
		 		differences += t.differences.count
		 	end
		 %>
		 <tr class="<%= (differences > 0 ? 'error' : 'success') %>">
		 	<td><%= link_to 'Счет-фактуры против ПТУ', sfptu_tests_path %></td>
		 	<td><i class="<%= (differences > 0 ? 'icon-remove' : 'icon-ok') %>"></i></td>
		 	<td><%= "#{differences}" %></td>
		 </tr>
		 <%
		 	differences = 0
		 	@rcvbls_tests.each do |t|
		 		differences += t.differences.count
		 	end
		 %>
		 <tr class="<%= (differences > 0 ? 'error' : 'success') %>">
		 	<td><%= link_to 'Взаиморасчеты ', rcvbls_tests_path %></td>
		 	<td><i class="<%= (differences > 0 ? 'icon-remove' : 'icon-ok') %>"></i></td>
		 	<td><%= "#{differences}" %></td>
		 </tr>
	</tbody>
	<tfoot>
		<%
		 	differences = 0
		 	@all_tests.each do |t|
		 		differences += t.differences.count
		 	end
		 %>
		 <tr class="<%= (differences > 0 ? 'error' : 'success') %>">
		 	<td><%= link_to 'ИТОГО', all_tests_path %></td>
		 	<td><i class="<%= (differences > 0 ? 'icon-remove' : 'icon-ok') %>"></i></td>
		 	<td><%= "#{differences}" %></td>
		 </tr>
	</tfoot>
</table>

<h2>Тесты по магазинам</h2>
<table class="table table-condensed">
	<thead>
		<th>Магазин</th>
		<th>Статус</th>
		<th>Тестов</th>
		<th>Расхождений</th>
	</thead>
	<tbody>
		<%= render @stocks %>
	</tbody>
</table>

<h2>Тесты по организациям</h2>
<table class="table table-condensed">
	<thead>
		<th>Организация</th>
		<th>Статус</th>
		<th>Тестов</th>
		<th>Расхождений</th>
	</thead>
	<tbody>
		<%= render @organizations %>
	</tbody>
</table>